config/routes.rb
Rails.application.routes.draw do

  root to:"homes#top"

  # メソッド'URL' => 'こんとろーる＃あくしょん'，as:'名前付きルート'
  get 'home/about' => 'homes#about' ,as:'about'

  devise_for :users

  resources :users, only: [:index, :show, :edit, :update]
  resources :books, only: [:index, :show, :edit, :new, :create, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 resources :groups, only: [:index, :show, :create, :new, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   has_one_attached :profile_image

   belongs_to :user

   has_many :view_counts, dependent: :destroy

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }


end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
   belongs_to :owner, class_name: 'User'
   has_many :group_users, dependent: :destroy
   has_many :users, through: :group_users

   validates :name, presence: true
   validates :introduction, presence: true

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
  # （パスワードの正確性を検証）
  :registerable,
  # （ユーザ登録や編集、削除）
  :recoverable,
  # （パスワードをリセット）
  :rememberable,
  # （ログイン情報を保存）
  :validatable
  # （email のフォーマットなどのバリデーション）

    has_one_attached :profile_image

    has_many :books,dependent: :destroy
    has_many :view_counts, dependent: :destroy
    has_many :group_users, dependent: :destroy
    has_many :groups, through: :group_users

    def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
    end

    validates :name,
    presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
    validates :introduction, length: { maximum: 50 }



end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end






  protected


  # (名前登録メソッド)
  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  # def configure_permitted_parameters
  # devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  # end



end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    # 新規登録
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:success] = 'You have created book successfully.'
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new

  end

  def show
    @book_find = Book.find(params[:id])
    @user = @book_find.user
    @book = Book.new
    unless ViewCount.find_by(user_id: current_user.id, book_id: @book_find.id)
      current_user.view_counts.create(book_id: @book_find.id)
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
     render "edit"
    else
     redirect_to books_path
    end
  end


  def update
   @book = Book.find(params[:id])
   if @book.update(book_params)
  flash[:success] = 'You have updated book successfully.'
   redirect_to book_path(@book.id)
   else
   render :edit
   end
  end


  def destroy
   @book = Book.find(params[:id])
   @book.destroy
   redirect_to books_path

  end



  # ストロングパラメータ

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.save
  end

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end


private

  def group pramas
  params.require(:groups).permit(:name, :introduction, :image)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController


  def top
  end

  def about

     
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book =Book.new



  end


  def edit
    @user = User.find(params[:id])
    if @user == current_user
     render "edit"
    else
     redirect_to user_path(current_user)
    end
  end

  def update
     @user = User.find(params[:id])
     if @user.update(user_params)
        flash[:success] = 'You have updated user successfully.'
       redirect_to user_path(@user.id)
     else
      render :edit
     end

  end


   private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.errors.html.erb
<div><% if book.errors.any? %>
  <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
  <ul>
    <% book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
</div>

app/views/books/_book.html.erb
  <div class="col-md-3">
   <h2 class="mt-3">New book</h2>
    <%= form_with model:book do |f| %>
     <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class: "form-control book_title" %>
     </div>
     <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class: "form-control book_body" %>
     </div>
     <div class="form-group">
       <%= f.submit'Create Book', class: "btn btn-success" %>
     </div>
     <% end %>
  </div>
 </div>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>



<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  <h1>Editing Book</h1>
  <%= form_with model:@book do |f| %>
  <div class="form-group">
    <label for ="inputtitle">Title</label>
    <%= f.text_field :title, autofocus: true, id:"inputtitle", class: "form-control book_title" %>
  </div>
  <div class="form-group">
    <label for ="inputbody">Opinion</label>
    <%= f.text_area :body, autofocus:true, id:"inputbody", class: "form-control book_body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Book", class: "btn btn-success" %>
  </div>
  <% end %>

<%= link_to "Show",book_path(@book) %> | <%= link_to "Back",books_path %>

</div>

app/views/books/index.html.erb
<%= render 'books/book.errors',book: @book %>
<%= render 'users/user',user: @user %>
<%= render 'books/book',book: @book %>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opnion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
         <% if book.user.profile_image.attached? %>
         <%= image_tag book.user.profile_image %>
         <% else %>
         <%= image_tag 'no_image' %>
         <% end %>
         <% end %>
        </td>
        <td>
         <%= link_to book_path(book) do %>
         <%= book.title %>
        <% end %>
        </td>
        <td>
         <%= book.body %>
        </td>
        <% end %>
       </tr>
    </tbody>
  </table>
  <%= link_to "グループ作成", new_group_path %>
</div>

app/views/books/show.html.erb
<%= render 'books/book.errors',book: @book %>
<%= render'users/user',user: @user %>
<%= render 'books/book',book: @book %>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table">
    <tbody>
      <tr>
        <td>
          <%= link_to user_path(@user) do %>
          <% if @user.profile_image.attached? %>
          <%= image_tag @user.profile_image %>
          <% else %>
          <%= image_tag 'no_image' %>
          <% end %>
           <%= @book_find.user.name %>
           <% end %>
        </td>
        <td><%= @book_find.title %></td>
        <td><%= @book_find.body %></td>
        <td><% if @book_find.user == current_user %>
            <%= link_to "Edit", edit_book_path(@book_find), class: "btn btn-sm btn-success" %>
            <% end %>
        </td>
        <td>
            <% if @book_find.user == current_user %>
            <%= link_to "Destroy", book_path(@book_find), method: :delete ,"data-confirm" => "本当に消しますか?", class: "btn btn-sm btn-danger" %>
            <% end %>
        </td>
        <td><p class="view-counts">数：<%= @book_find.view_counts.count %></p></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<h1>グループ新規作成</h1>

app/views/homes/about.html.erb
<h1>welcome to <i class="fas fa-book"></i>
<strong>Bookers!!</strong></h1>

app/views/homes/top.html.erb
<main>
  <div class="container">
      <div class="row">
         <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">


         <h1>welcome to <i class="fas fa-book"></i>
         <strong>Bookers!!</strong></h1>

         <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>

         <p>you can share and exchange your opinions , inpressions , and emotions</p><br>

         <p>about various books!</p>

          <div class="btn-wrapper col-10 mx-auto">
             <div class="row">
              <%= link_to "Log in",new_user_session_path , class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
             </div>
            <div class="row">
              <%= link_to "Sign up",new_user_registration_path , class: "btn btn-success btn-sm btn-block sign_up" %>
            </div>
          </div>
         </div>
      </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/5f2329857c.js" crossorigin="anonymous"></script>
  </head>

  <body>
   <% flash.each do |key, value| %>
   <%= content_tag(:div, value, class: "#{key}") %>
   <% end %>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
     <div class="container">
      <%= link_to root_path, class: "navbar-brand" do %>
      <span>Bookers</span>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
      </button>
      <div class = "navbar-collapse collapse" id="navbarNavDropdown">

       <ul class="navbar-nav ml-auto">
       <% if user_signed_in? %>
       <%= link_to user_path(current_user.id), class: "nav-item nav-link text-light" do %><i class="fas fa-home"></i> Home<%end%>
       <%= link_to users_path, class: "nav-item nav-link text-light" do %><i class="fas fa-users"></i> Users<%end%>
       <%= link_to books_path, class: "nav-item nav-link text-light" do %><i class="fas fa-book-open"></i> Books<%end%>
       <%= link_to destroy_user_session_path, method: :delete, class: "nav-item nav-link text-light" do %><i class="fas fa-sign-out-alt"></i> Log out<%end%>

        <% else %>
       <%= link_to root_path, class: "nav-item nav-link text-light" do %><i class="fas fa-home"></i> Home<%end%>
       <%= link_to about_path, class: "nav-item nav-link text-light" do %><i class="fas fa-link"></i> About<%end%>
       <%= link_to new_user_registration_path, class: "nav-item nav-link text-light" do %><i class="fas fa-user-plus"></i> Sign up<%end%>
       <%= link_to new_user_session_path, class: "nav-item nav-link text-light" do %><i class="fas fa-sign-in-alt"></i> Log in<%end%>
       <% end %>
       </ul>
      </div>
     </div>
    </nav>
   </header>

   <main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
     <div class="row">
      <div class="col-md-3">
       <div class="col-md-3">
        <div class="col-md-8 offset-md-1">
        </div>
       </div>
      </div>
     </div>
    </div>
    <%= yield %>
   </main>



   <footer>
    <div class ="container mt-5">
      <div class ="row">
        <div class="mx-auto">
        <p> CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
   </footer>
  </body>
</html>

app/views/users/_user.html.erb
  <div class="col-md-3">
    <h2>User info</h2>
     <% if user.profile_image.attached? %>
     <%= image_tag user.profile_image%>
     <% else %>
     <%= image_tag 'no_image' %>
     <% end %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
     <tr>
       <th>introduction</th>
       <th><%= user.introduction %></th>
     </tr>
    </tbody>
  </table>

  <div class="row">
  <%= link_to edit_user_path(user) , class: "btn btn-outline-secondary btn-block" do %>
  <span class="fas fa-user-cog"></span>
  <% end %>
  </div>

</div>
</div>
</div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>errors prohibited this obj from being saved:
  <% @user.errors.full_messages.each do |message| %>
      <%= message %>
  <% end %>
<% end %>



 <div class="container">
   <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
       <h1>User info</h1>
        <%= form_with model:@user do |f| %>
         <div class="form-group">
          <label for ="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name" %>
         </div>
         <div class="form-group">
           <label for="inputImage">Image</label>
           <%= f.file_field :profile_image, placeholder: "Introduction", accept: "image/*", class: "form-control-file profile_image" %>
         </div>
         <div class="form-group">
            <label for="inputtext">introduction</label>
             <%= f.text_area :introduction, autofocus: true, id:"inputtext", class: "form-control introduction" %>
         </div>
         <div class="form-group">
            <%= f.submit "Update User", class: "btn btn-secondary" %>
            <% end %>
         </div>
     </div>
   </div>
 </div>

app/views/users/index.html.erb
<%= render'books/book.errors',book: @book %>
<%= render'user',user: @user %>
<%= render 'books/book',book: @book %>

<div class="col-md-8 offset-md-1">
 <h2>Users</h2>s
 <table class="table">
  <thead>
   <tr>
    <th>image</th>
    <th>name</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
   <% @users.each do |user| %>
   <tr>
    <td>
      <% if user.profile_image.attached? %>
      <%= image_tag user.profile_image %>
      <% else %>
      <%= image_tag 'no_image' %>
      <% end %>
    </td>
    <td><%=user.name %></td>
    <td><%= link_to "Show" , user_path(user) %></td>
    <% end %>
   </tr>
  </tbody>
 </table>

</div>

app/views/users/show.html.erb
<%= render 'books/book.errors',book: @book %>
<%= render'user',user: @user %>
<%= render 'books/book',book:@book %>



<!--ユーザー投稿一覧-->

<div class="col-md-8 offset-md-1">
 <h3>Books</h3>

<table class="table table-hover table-inverse">

  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <% @books.each do |book| %>
    <tr>
     <td>
      <%= link_to user_path(@user) do %>
       <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image %>
       <% else %>
        <%= image_tag 'no_image' %>
       <% end %>
       <% end %>
     </td>
     <td>
      <%= link_to book_path(book) do%>
      <%= book.title %>
      <% end %>
     </td>
     <td> <%= book.body %> </td>
      <% end %>
    </tr>
  </tbody>

</table>

</div>